### ISSUE TITLE
Dosrat bug

### ISSUE THREAD

**Issue by cinquanta0** [Criper98/DOSrat-2.0#1]
Ciao, sono quello di yt. Vorrei spiegare meglio tutti i bug.
1 Allora, come prima cosa quando uso il portforwarding ho seguito tutti i passaggi e quando inserisco un dispositivo(il mio PC) esce un altro indirizzo invece di quello statico nonostante lo abbia cambiato... e quindi poi quando clicco sul virus con anydesk sul pc vittima non va.
2 Ho provato poi con ngrok collegando l'account ovviamente e poi ho inserito il comando ngrok tcp 6969... poi quando si apre quella schermata nella creazione del client ho inserito tutti i dati e l ho creato... noto un leggero miglioramento perché inizialmente va ma poi ne escono 5 client connessi forse perché avrò fatto casino io...(Eppure ogni volta gli elimino i client).
Dovrei provare a disinstallare l'app ogni volta che creo un client? Quando avvio il client col pc vittima non si avvia, rimane nella task menager ma è ancora visibile sul desktop! Eppure ogni volta gli elimino i client

Spero di essere stato chiaro. Se dovessi avere altri problemi non esiterò a scriverti!

**Comment by Criper98** [comment]
1) Che indirizzo hai scritto come host del Client? 
Se procedi tramite port forwarding devi inserire il tuo indirizzo IP pubblico, non privato, ovvero se comincia con 192.168 allora è quello privato, per sapere il tuo indirizzo IP pubblico basta chiederlo su Google.
In questo modo, se hai impostato correttamente il port forwarding, quando avvii il Client esso si connetterà al tuo pc, se ciò non accade potresti aver configurato male il port forwarding o potresti avere la porta che hai deciso di usare chiusa sul firewall del tuo pc.

2) Ti escono 5 Client perché immagino avrai fatto diverse prove, in teoria se riavvii il pc non dovrebbero più uscirti Client siccome ti dovrebbe rimanere solo il primo Client che hai avviato, se non ti esce nulla connesso è perché quel primo Client che hai creato non riesce a connettersi, probabilmente lo avevi impostato con un IP che non è più valido.
Il Client funziona in questo modo: La prima volta che lo apri su un pc nel quale non lo avevi mai avviato lui si installa 
nella cartella che scegli dal menu di creazione del Client. Terminata l'installazione si elimina in automatico il file .exe originale da cui lo hai avviato. Una volta che è installato cercherà di connettersi all'indirizzo IP che tu gli hai specificato durante la creazione.
Siccome l'installazione è persistente, quando riavvii il pc il Client rimarrà presente e si avvierà in automatico insieme a Windows. Per rimuovere il Client devi connetterti a esso con DOSrat e lanciare il comando Uninstall. Per rimuoverlo manualmente invece devi terminarlo dal Task Manager, poi devi eliminare il file .exe dalla cartella in cui lo hai installato, e in fine devi eliminare la seguente chiave di registro dal registro di sistema: HKEY_CURRENT_USER\SOFTWARE\Windows Update
Detto ciò quando tu provi ad avviare un altro Client in un pc che è già infettato, accade che il nuovo Client si avvierà soltanto senza installarsi (quindi rimane nel desktop), e si avvierà insieme al Client che è già installato sul pc, quindi ti ritroverai più Client, anche se elimini il file non cambia nulla una volta che lo hai avviato, come ti ho detto prima dovresti riavviare il pc (o terminare tutti i Client nel Task Manager). Se invece hai già un Client installato e connesso al tuo pc e vuoi aggiornarlo con un altro puoi usare il comando Update per fare ciò.

Ad ogni modo farò un aggiornamento in cui cambierò il sistema d'installazione del Client in modo da prevedere problemi come questo in cui se un Client è già installato quello nuovo deve sostituirlo.

**Comment by cinquanta0** [comment]
C'è un problema infatti nel port forwarding... quando inserisco una nuova porta e configuro tutto seleziono il pc ma poi esce quando clicco applica che l'ip riservato è diverso rispetto a quello del pc; penso che sia questo il problema allora... ho skywifi.
Sai come posso modificarlo? Anche se mi sembra strano...oppure sapresti come disattivare le impostazioni firewall, casomai è questo il problema

**Comment by Criper98** [comment]
Guardando in giro mi sembra che il procedimento che fai nel port forwarding sia giusto, magari prova a riavviare il modem. Per essere sicuro al 100% che hai impostato correttamente un IP statico sul tuo PC prova ad avviare il cmd e a lanciare il comando "ipconfig", nella scheda di rete che usi per connetterti al wifi controlla che la voce "Indirizzo IPv4" abbia l'IP che hai scelto tu, in caso contrario potresti aver configurato male l'IP statico.

![image](https://github.com/Criper98/DOSrat-2.0/assets/62108281/c8f065c7-2381-479d-8215-091359c581f6)

**Comment by cinquanta0** [comment]
ho provato a riavviare il modem... in caso riprovo ma l'ultima cifra avevo messo 155 forse devo cambiarla

**Comment by cinquanta0** [comment]
come faccio ad eliminare la chiave di registro? Casomai è questo il problema

**Comment by cinquanta0** [comment]
una domanda ma c'è un modo per bypassare l'anticivirus del virus così non se n'è accorge?

**Comment by Criper98** [comment]
Puoi eliminare la chiave di registro usando l'editor del registro di sistema di Windows, scrivendo "Regedit" sul menu start dovrebbe uscirti il programma.

La questione dell'antivirus è complessa, per ora ho implementato la possibilità di bypassare l'UAC, se il Client riesce a farlo allora puoi aggiungerlo alle esclusioni dell'AV sempre tramite apposito comando, però prima di tutto il Client dev'essere installato sul pc. Ovviamente funziona solo con l'antivirus di Windows, se hai installato un antivirus buono di terze parti l'unica soluzione è aggiungere il Client nelle esclusioni a mano.
Ovviamente farlo sul pc di un'altra persona senza il suo consenso è illegale, io non mi assumo nessuna responsabilità riguardo l'utilizzo illecito di DOSrat o eventuali danni che potrebbe causare, questo progetto è solo a scopo informativo ed educativo.

**Comment by cinquanta0** [comment]
sisi lo so infatti non lo faccio a lui più... lo sto provando sulla macchina virtuale. Una cosa ma dopo aver fatto regedit e si apre il programma cosa devo eliminare casomai faccio casino

**Comment by Criper98** [comment]
Scusa il ritardo della risposta, comunque dovresti eliminare la seguente chiave di registro (cartella) HKEY_CURRENT_USER\SOFTWARE\Windows Update

**Comment by ShAmPooTool** [comment]
ciao ho un problema con il client praticamente appena il client viene eseguito 
![Immagine 2023-07-05 040859](https://github.com/Criper98/DOSrat-2.0/assets/92433912/54072d95-d82b-48f5-9dc5-b6b2b05bf7e6)
ti viene fuori questa scritta

**Comment by Criper98** [comment]
Ciao, nell'ultimo aggiornamento [2.0.0-b.7](https://github.com/Criper98/DOSrat-2.0/releases/tag/2.0.0-b.7) ho aggiunto il comando **Reinstall** che ti permette di ripetere la procedura di installazione del Client, quindi anche se hai avviato molteplici Client su un PC, una volta che sei riuscito ad avviare quello giusto che ti permette di connetterti, ti basterà eseguire il comando **Reinstall** e riavviare il PC per ritrovarti solo con il Client corretto installato.
