### ISSUE TITLE
Client Bug

### ISSUE THREAD

**Issue by ShAmPooSex** [Criper98/DOSrat-2.0#2]
ciao ho avuto questo problema con il software, ovvero quando il client viene creato non viene poi generato

**Comment by Criper98** [comment]
La visualizzazione dei file nascosti era disattivata su Windows.
Quando si genera un Client, se l'impostazione per renderlo un file nascosto è attiva questo verrà generato e successivamente gli verrà applicato l'attributo di file nascosto, se l'opzione di Windows per vedere tali file è disattivata il Client sarà presente nella cartella ma non visibile.

Per attivare la visualizzazione dei file nascosti si puoi seguire questa guida: https://youtu.be/SLvHzL12028
Win11: https://youtu.be/qCGaPMjWtaw
