### ISSUE TITLE
client creato non si avvia

### ISSUE THREAD

**Issue by Nahz123** [Criper98/DOSrat-2.0#3]
**Describe the bug**

**To Reproduce**
1. Go to 'Dosrat'
2. Click on 'crea un client'
3. Scroll down to 'crea client'

**Expected behavior**

**Screenshots**
non si apre il client creato 

**Environment (please complete the following information):**
 - OS: [e.g. Win 11]
 - DOSrat Version [e.g. 2.0.6]
 - Client Version [e.g. 2.0.6]

**Additional context**
non si apre il client creato

**Comment by Criper98** [comment]
Cosa intendi con "Non si apre", ti da un errore? Hai controllato se sul task manager lo vedi tra i programmi in esecuzione? Con quali impostazioni lo hai creato?

**Comment by Criper98** [comment]
Chiuso per inattività.
